### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [swong11/splurty-app#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by swong11** [comment]
Thanks Marco! I pushed some new commits. Is it better?

**Comment by MarcoMorawec** [comment]
@swong11 looks like you added the mobile meta tag in your code. :+1: 

If you pushed you code live to production (aka heroku) you should see a big difference on your mobile phone. I just tested it and did not see a difference on my phone, so you either still have to push up to Heroku or double check your code.

I'm sure you can figure it out :)

**Comment by swong11** [comment]
Oops I forgot to push to heroku, should be up now. Thanks!

**Comment by MarcoMorawec** [comment]
@swong11 :+1: 

Make sure you close the issue, now that you solved it.
